---
- name: Change ownership of /minio directory
  ansible.builtin.file:
    path: /home/{{ user }}/minio
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'
  tags: postdeploy

- name: Reboot
  reboot:
