---
- name: Create /home/{{ user }}/.kube directory
  ansible.builtin.file:
    path: /home/{{ user }}/.kube
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'
  tags: k3s

- name: Create kind directory
  ansible.builtin.file:
    path: /home/{{ user }}/kind
    state: directory
    mode: '0777'
    owner: "{{ user }}"
    group: "{{ user }}"
  tags: k3s

- name: Copy kind-config file
  ansible.builtin.copy:
    src: files/kind-config.yaml
    dest: /home/{{ user }}/kind
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0777'
  tags: k3s

#- name: Download and install k3s server
#  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable traefik agent --snapshotter=native" K3S_KUBECONFIG_MODE="644" sh -s -
#  tags: k3s

- name: Download and install podman
  shell: sudo apt-get update -y && sudo apt install podman && sudo sed -i "s/# unqualified-search-registries.*/unqualified-search-registries\ =\ [\"docker.io\"]/" /etc/containers/registries.conf && sudo apt install podman-docker && sudo apt install python3-pip && pip3 install podman-compose --break-system-packages
  args:
    chdir: /home/{{ user }}/kind
  tags: k3s

- name: Download and install kind
  shell: curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64 && chmod +x ./kind && sudo mv ./kind /usr/local/bin/kind
  args:
    chdir: /home/{{ user }}/kind
  tags: k3s

- name: Delete kind cluster
  become_user: "{{ user }}"
  shell: kind delete cluster
  args:
    chdir: /home/{{ user }}/kind
  tags: k3s

- name: Create kind cluster
  become_user: "{{ user }}"
  shell: kind create cluster --config kind-config.yaml
  args:
    chdir: /home/{{ user }}/kind
  tags: k3s

- name: Install ingress-nginx
  become_user: "{{ user }}"
  shell: helm upgrade --install ingress-nginx ingress-nginx --version 4.4.2 --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace --set controller.replicaCount=1 --set controller.ingressClassResource.default=true --set controller.service.nodePorts.http=31000 --set controller.service.nodePorts.https=31001 --set controller.service.ports.http=8080 --set controller.service.ports.https=8443
  tags: k3s