---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: security

- hosts: webservers #lab_servers
  gather_facts: yes
  become: yes
  roles:
    - role: docker
    - role: lab_server
    - role: k3s
    - role: containers/certbot
    - role: haproxy
    - role: code-server
    - role: minio
    - role: post-deploy
